language: go

go:
  - 1.12.x
  - master

install: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

env:
  global:
    - GO111MODULE=on
    - ARN_ROOT=$HOME/notify.moe

before_script:
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/before-script.sh)

  # Download main repo to access API keys
  - git clone --depth=1 https://github.com/animenotifier/notify.moe $ARN_ROOT

  # Database
  - git clone --depth=1 https://github.com/animenotifier/database ~/.aero/db/arn

script:
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/script.sh)

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/after-success.sh)