language: go

go:
  - 1.11.x
  - master

install: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/before-script.sh)

  # Download main repo to access API keys
  - git clone --depth=1 https://github.com/animenotifier/notify.moe $GOPATH/src/github.com/animenotifier/notify.moe

  # Database
  - git clone --depth=1 https://github.com/animenotifier/database ~/.aero/db/arn

script:
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/script.sh)

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/after-success.sh)